name: Build & Push to Artifactory

on:
  #   pull_request:
  #     branches:
  #       - "main"

  push:
    branches:
      - "artifactory"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: arc-runner-lacework-generic-medium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Artifactory Authentication
        id: auth_artifactory
        uses: lacework-dev/actions/auth-artifactory-v1@main

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://artifactory.ops.lacework.engineering
          JF_ACCESS_TOKEN: ${{ steps.auth_artifactory.outputs.ARTIFACTORY_ACCESS_TOKEN }}
